### ISSUE TITLE
Add new client config DNS flags

### ISSUE THREAD

**Issue by nwaldispuehl** [freifunkMUC/wg-access-server-chart#17]
With https://github.com/freifunkMUC/wg-access-server/commit/45a872b0d8283ffdf8951a67291c0220ec0b8d6d we added new configuration items to override DNS entries in the wg-quick client config file.

Sample configuration in the server config file:
```
...
clientConfig:
  dnsServers:
    - 10.10.20.80
    - 9.9.9.9
    - 2001:4860:4860::8888
  dnsSearchDomain: mydomain.com

...
```
Which leads to the following entry in the downloadable wg-quick client config file:
```
[Interface]
...
DNS = 10.10.20.80, 9.9.9.9, 2001:4860:4860::8888, mydomain.com
...
```
These should also be adjustable in the charts `values.yaml`.
